#!/usr/bin/env python
"""
Gather and simplify test cases generated by afl
"""
import sys
import os
from glob import glob

if len(sys.argv) < 5:
    print("Usage: %s sync_dir gather_dir fixed_dir /path/to/executable"%sys.argv[0])
    sys.exit(0)

sync_dir = sys.argv[1]
gather_dir = sys.argv[2]
fixed_dir = sys.argv[3]
executable = sys.argv[4]
try:
    os.mkdir(gather_dir)
except OSError:
    pass
try:
    os.mkdir(fixed_dir)
except OSError:
    pass

# gather everything
for id,fname in enumerate(glob("%s/*/crashes/*"%sync_dir)):
    outname = "crashes/%08d"%id
    with open(outname, 'w') as of:
        with open(fname) as inf:
            of.write(inf.read())

# minimize everything
dirs = glob("%s/*"%gather_dir):
for i, ifname in enumerate(dirs):
    ofname = fixed_dir + '/' + '/'.join(ifname.split('/')[1:])
    print "Simplifying %s (%d/%d)"%(ifname, i, len(dirs))
    os.system("afl-tmin -i %s -o %s %s > /dev/null"%(ifname, ofname, executable))
